<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ovap"
    nsURI="ovap" nsPrefix="ovap">
  <eSubpackages name="video" nsURI="video" nsPrefix="video">
    <eSubpackages name="filter" nsURI="filter" nsPrefix="filter">
      <eSubpackages name="filtersetup" nsURI="http:///ovap.video.filter.filtersetup/1.0.0"
          nsPrefix="filtersetup">
        <eClassifiers xsi:type="ecore:EClass" name="FilterInstance" eSuperTypes="#//video/filter/filtersetup/Identifiable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
              eType="#//video/filter/filtersetup/FilterType" eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="portInInstance" upperBound="-1"
              eType="#//video/filter/filtersetup/PortInInstance" containment="true"
              eOpposite="#//video/filter/filtersetup/PortInInstance/filterInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="portOutInstance"
              upperBound="-1" eType="#//video/filter/filtersetup/PortOutInstance"
              containment="true" eOpposite="#//video/filter/filtersetup/PortOutInstance/filterInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
              eType="#//video/filter/filtersetup/Configuration" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FilterType" eSuperTypes="#//video/filter/filtersetup/Identifiable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="portOut" upperBound="-1"
              eType="#//video/filter/filtersetup/PortOut" containment="true" eOpposite="#//video/filter/filtersetup/PortOut/filterType"
              eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="portIn" upperBound="-1"
              eType="#//video/filter/filtersetup/PortIn" containment="true" eOpposite="#//video/filter/filtersetup/PortIn/filterType"
              eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//video/filter/filtersetup/FilterModel"
              eOpposite="#//video/filter/filtersetup/FilterModel/filterTypes"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FiltersSetup" eSuperTypes="#//video/filter/filtersetup/Identifiable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterInstances"
              upperBound="-1" eType="#//video/filter/filtersetup/FilterInstance" containment="true"
              eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
              eType="#//video/filter/filtersetup/FilterConnection" containment="true"
              eOpposite="#//video/filter/filtersetup/FilterConnection/filtersSetup"
              eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//video/filter/filtersetup/FilterModel"
              eOpposite="#//video/filter/filtersetup/FilterModel/setup"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FilterConnection" eSuperTypes="#//video/filter/filtersetup/Identifiable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="portInInstance" lowerBound="1"
              eType="#//video/filter/filtersetup/PortInInstance" eOpposite="#//video/filter/filtersetup/PortInInstance/filterConnection"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="portOutInstance"
              lowerBound="1" eType="#//video/filter/filtersetup/PortOutInstance" eOpposite="#//video/filter/filtersetup/PortOutInstance/filterConnection"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="filtersSetup" eType="#//video/filter/filtersetup/FiltersSetup"
              eOpposite="#//video/filter/filtersetup/FiltersSetup/connections"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortIn" eSuperTypes="#//video/filter/filtersetup/Port">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterType" eType="#//video/filter/filtersetup/FilterType"
              eOpposite="#//video/filter/filtersetup/FilterType/portIn"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortOut" eSuperTypes="#//video/filter/filtersetup/Port">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterType" eType="#//video/filter/filtersetup/FilterType"
              eOpposite="#//video/filter/filtersetup/FilterType/portOut"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//video/filter/filtersetup/Identifiable"/>
        <eClassifiers xsi:type="ecore:EClass" name="PortInstance" abstract="true"
            eSuperTypes="#//video/filter/filtersetup/Identifiable"/>
        <eClassifiers xsi:type="ecore:EClass" name="PortInInstance" eSuperTypes="#//video/filter/filtersetup/PortInstance">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterInstance" lowerBound="1"
              eType="#//video/filter/filtersetup/FilterInstance" eOpposite="#//video/filter/filtersetup/FilterInstance/portInInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterConnection"
              lowerBound="1" eType="#//video/filter/filtersetup/FilterConnection"
              eOpposite="#//video/filter/filtersetup/FilterConnection/portInInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
              eType="#//video/filter/filtersetup/PortIn"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PortOutInstance" eSuperTypes="#//video/filter/filtersetup/PortInstance">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterInstance" lowerBound="1"
              eType="#//video/filter/filtersetup/FilterInstance" eOpposite="#//video/filter/filtersetup/FilterInstance/portOutInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterConnection"
              upperBound="-1" eType="#//video/filter/filtersetup/FilterConnection"
              eOpposite="#//video/filter/filtersetup/FilterConnection/portOutInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
              eType="#//video/filter/filtersetup/PortOut"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Identifiable">
          <eOperations name="eURIFragmentSegment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="body" value="&#xD;&#xA;&#x9;&#x9;//return ((Identifiable)eObject).getName();&#xD;&#xA;&#x9;&#x9;//String container=&quot;&quot;;&#xD;&#xA;&#x9;&#x9;//if(eObject.eContainer().eContainer()==null) // if root is our container&#xD;&#xA;&#x9;&#x9;//&#x9;container= ((Identifiable)eObject.eContainer()).getName()+&quot;/&quot;;&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;//return container + ((Identifiable)eObject).getName();&#xD;&#xA;&#x9;&#x9;return super.eURIFragmentSegment(eStructuralFeature, eObject);&#xD;&#xA;&#x9;"/>
            </eAnnotations>
            <eParameters name="eStructuralFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
            <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eOperations>
          <eOperations name="eObjectForURIFragmentSegment" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="body" value="&#xD;&#xA;&#x9;&#x9;// TODO: need to override getEObjectForURIFragmentRootSegment.getEObjectForURIFragmentRootSegment&#xD;&#xA;&#x9;&#x9;// to fully support hierarchical EObject paths&#xD;&#xA;&#x9;&#x9;//if(getName().equals(uriFragmentSegment))&#xD;&#xA;&#x9;&#x9;//&#x9;return this;&#xD;&#xA;&#x9;&#x9;&#xD;&#xA;&#x9;&#x9;//for(EObject eObject:eContents()){&#xD;&#xA;&#x9;&#x9;//&#x9;if(((Identifiable)eObject).getName().equals(uriFragmentSegment))&#xD;&#xA;&#x9;&#x9;//&#x9;&#x9;return eObject;&#xD;&#xA;&#x9;&#x9;//}&#xD;&#xA;&#x9;&#x9;//return null;&#xD;&#xA;&#x9;&#x9;return super.eObjectForURIFragmentSegment(uriFragmentSegment);&#xD;&#xA;&#x9;"/>
            </eAnnotations>
            <eParameters name="uriFragmentSegment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
              defaultValueLiteral=""/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ConfigurationMapEntry" instanceClassName="java.util.Map$Entry">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Configuration">
          <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
              eType="#//video/filter/filtersetup/ConfigurationMapEntry" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FilterModel" eSuperTypes="#//video/filter/filtersetup/Identifiable">
          <eStructuralFeatures xsi:type="ecore:EReference" name="filterTypes" upperBound="-1"
              eType="#//video/filter/filtersetup/FilterType" containment="true" eOpposite="#//video/filter/filtersetup/FilterType/model"
              eKeys="#//video/filter/filtersetup/Identifiable/name"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="setup" lowerBound="1"
              eType="#//video/filter/filtersetup/FiltersSetup" containment="true"
              eOpposite="#//video/filter/filtersetup/FiltersSetup/model"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
